import * as THREE from 'three';
import { Sky } from 'three/addons/objects/Sky.js';

const clamp = THREE.MathUtils.clamp;
const mat = (color, roughness=.8, metalness=0) => new THREE.MeshStandardMaterial({ color, roughness, metalness });
function mesh(parent, geometry, material, cast=true, receive=true){ const o=new THREE.Mesh(geometry,material);o.castShadow=cast;o.receiveShadow=receive;parent.add(o);return o; }
function box(parent,x,y,z,w,h,d,material){ const o=mesh(parent,new THREE.BoxGeometry(w,h,d),material);o.position.set(x,y,z);return o; }
function makeInst(parent,geo,material,count,cast=true,receive=true){const i=new THREE.InstancedMesh(geo,material,count);i.castShadow=cast;i.receiveShadow=receive;parent.add(i);return i;}
function setInstance(inst,index,pos,yaw=0,scale=1){const o=new THREE.Object3D();o.position.copy(pos);o.rotation.y=yaw;o.scale.setScalar(scale);o.updateMatrix();inst.setMatrixAt(index,o.matrix);}
function canvasMaterial(draw,w=512,h=128){const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');draw(ctx,w,h);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return new THREE.MeshBasicMaterial({map:t,toneMapped:false});}

export class RailwayWorld {
  constructor(scene, mission, renderer){
    this.scene=scene;this.mission=mission;this.renderer=renderer;this.group=new THREE.Group();scene.add(this.group);
    this.route=new THREE.CatmullRomCurve3(mission.routePoints.map(p=>new THREE.Vector3(...p)),false,'catmullrom',.5);this.length=this.route.getLength();this.signals=[];this.otherTrains=[];this.tunnel=mission.tunnel||null;
    this.materials={rail:mat(0x70787d,.3,.85),sleeper:mat(0x4a4038,.94),ballast:mat(0x666a68,1),grass:mat(0x40573b,1),grass2:mat(0x526b47,1),metal:mat(0x40474b,.55,.38),wire:mat(0x171b1e,.45,.8),concrete:mat(0xa8a8a2,.94),edge:mat(0xd7d0bf,.9),roof:mat(0x384249,.6,.2),dark:mat(0x111417,.6,.15),trunk:mat(0x5a422f,1),leaf:mat(0x355a35,1),road:mat(0x2d3235,.95)};
    this.setupLighting();this.buildGround();this.buildTrack();this.buildLandscape();this.buildStations();this.buildSignals();this.buildTunnel();this.buildTraffic();this.buildRain();
  }
  sample(u,offset=0){u=clamp(u,0,1);const p=this.route.getPointAt(u),t=this.route.getTangentAt(u).normalize(),right=new THREE.Vector3(-t.z,0,t.x).normalize();if(offset)p.addScaledVector(right,offset);return{p,t,right,yaw:Math.atan2(t.x,t.z)};}
  speedLimit(u){let v=this.mission.speedZones[0][1];for(const [at,limit] of this.mission.speedZones)if(u>=at)v=limit;return v;}
  gradient(u){let v=0;for(const [at,g] of this.mission.gradients||[])if(u>=at)v=g;return v;}
  inTunnel(u){return !!this.tunnel&&u>=this.tunnel[0]&&u<=this.tunnel[1];}
  zone(u){for(const [a,b,z] of this.mission.environment||[])if(u>=a&&u<b)return z;return'country';}
  upcomingSignal(u){return this.signals.find(s=>s.u>u)||null;}

  setupLighting(){
    const night=this.mission.weather==='night',rain=this.mission.weather==='rain';
    const sky=new Sky();sky.scale.setScalar(300000);this.scene.add(sky);this.sky=sky;
    const uniforms=sky.material.uniforms;uniforms.turbidity.value=rain?14:7;uniforms.rayleigh.value=night?.18:2;uniforms.mieCoefficient.value=.008;uniforms.mieDirectionalG.value=.8;
    const sv=new THREE.Vector3().setFromSphericalCoords(1,THREE.MathUtils.degToRad(night?94:rain?72:54),THREE.MathUtils.degToRad(190));uniforms.sunPosition.value.copy(sv);
    this.scene.background=new THREE.Color(night?0x07101b:rain?0x8799a3:0xaec5d1);this.scene.fog=new THREE.FogExp2(night?0x09121d:rain?0x8799a3:0xaec5d1,night?.0022:rain?.002:.00105);
    this.hemi=new THREE.HemisphereLight(night?0x35435b:0xe8f4ff,night?0x050608:0x33462e,night?.4:1.55);this.scene.add(this.hemi);
    this.sun=new THREE.DirectionalLight(night?0x7890b9:0xffefd2,night?.18:rain?.85:3);this.sun.position.set(-80,125,110);this.sun.castShadow=!night;this.sun.shadow.mapSize.set(2048,2048);this.sun.shadow.camera.left=-90;this.sun.shadow.camera.right=90;this.sun.shadow.camera.top=90;this.sun.shadow.camera.bottom=-90;this.scene.add(this.sun);
  }
  buildGround(){const items=[];for(let i=0;i<120;i++){const s=this.sample(i/119);items.push(s);}const g=makeInst(this.group,new THREE.BoxGeometry(170,.9,170),this.materials.grass,items.length,false,true);items.forEach((s,i)=>{const p=s.p.clone();p.y=-.65;setInstance(g,i,p,s.yaw)});g.instanceMatrix.needsUpdate=true;}
  buildTrack(){
    const sleepers=[],rails=[],ballast=[],poles=[],arms=[],wires=[];const N=1200;
    for(let i=0;i<N;i++){const u=i/(N-1),s=this.sample(u);if(i%2===0){sleepers.push([s.p.clone(),s.yaw]);sleepers.push([s.p.clone().addScaledVector(s.right,4.55),s.yaw]);}if(i%6===0){ballast.push([s.p.clone(),s.yaw]);ballast.push([s.p.clone().addScaledVector(s.right,4.55),s.yaw]);}if(i%3===0)for(const off of[-.76,.76,3.79,5.31])rails.push([s.p.clone().addScaledVector(s.right,off),s.yaw]);if(i%27===0){poles.push([s.p.clone().addScaledVector(s.right,-4.2),s.yaw]);poles.push([s.p.clone().addScaledVector(s.right,8.5),s.yaw]);arms.push([s.p.clone().addScaledVector(s.right,2.15),s.yaw]);}if(i%12===0){wires.push([s.p.clone(),s.yaw]);wires.push([s.p.clone().addScaledVector(s.right,4.55),s.yaw]);}}
    const sl=makeInst(this.group,new THREE.BoxGeometry(2.72,.15,.27),this.materials.sleeper,sleepers.length),rl=makeInst(this.group,new THREE.BoxGeometry(.095,.14,6.2),this.materials.rail,rails.length),bl=makeInst(this.group,new THREE.BoxGeometry(4.35,.24,6.4),this.materials.ballast,ballast.length,false,true),po=makeInst(this.group,new THREE.BoxGeometry(.16,7,.16),this.materials.metal,poles.length),ar=makeInst(this.group,new THREE.BoxGeometry(12.7,.12,.12),this.materials.metal,arms.length),wi=makeInst(this.group,new THREE.BoxGeometry(.026,.026,15.5),this.materials.wire,wires.length,false,false);
    sleepers.forEach((v,i)=>{v[0].y=.04;setInstance(sl,i,v[0],v[1])});rails.forEach((v,i)=>{v[0].y=.16;setInstance(rl,i,v[0],v[1])});ballast.forEach((v,i)=>{v[0].y=-.1;setInstance(bl,i,v[0],v[1])});poles.forEach((v,i)=>{v[0].y=3.5;setInstance(po,i,v[0],v[1])});arms.forEach((v,i)=>{v[0].y=6.85;setInstance(ar,i,v[0],v[1])});wires.forEach((v,i)=>{v[0].y=6.35;setInstance(wi,i,v[0],v[1])});[sl,rl,bl,po,ar,wi].forEach(o=>o.instanceMatrix.needsUpdate=true);
  }
  buildLandscape(){
    const trees=[];const buildings=[];
    for(let i=5;i<330;i++){const u=i/334,s=this.sample(u),zone=this.zone(u);for(const side of[-1,1]){if(Math.random()>.7)continue;const lateral=(zone==='dense'?13:17)+Math.random()*(zone==='country'?58:34),p=s.p.clone().addScaledVector(s.right,side*lateral);if(zone==='wood'||zone==='country'||(zone==='suburb'&&Math.random()<.5)){trees.push([p,.65+Math.random()*1.2]);}else buildings.push([p,s.yaw,zone]);}}
    const tr=makeInst(this.group,new THREE.BoxGeometry(.32,2.3,.32),this.materials.trunk,trees.length),cr=makeInst(this.group,new THREE.ConeGeometry(1.35,4.1,9),this.materials.leaf,trees.length);trees.forEach(([p,sc],i)=>{const a=p.clone();a.y=1.15*sc;setInstance(tr,i,a,0,sc);const b=p.clone();b.y=3.65*sc;setInstance(cr,i,b,0,sc)});tr.instanceMatrix.needsUpdate=cr.instanceMatrix.needsUpdate=true;
    buildings.forEach(v=>this.makeBuilding(...v));for(const cfg of[[.08,1,22],[.22,-1,24],[.48,1,26],[.67,-1,20],[.87,1,22]])this.makeRoad(...cfg);
  }
  makeBuilding(p,yaw,zone){const dense=zone==='dense'||zone==='urban',w=dense?9+Math.random()*12:6+Math.random()*5,d=dense?12+Math.random()*18:8+Math.random()*8,h=dense?11+Math.random()*28:5+Math.random()*6,g=new THREE.Group(),wall=mat([0xb5afa5,0x98958f,0xc3baa9,0xaab0b3][Math.floor(Math.random()*4)],.92),win=new THREE.MeshStandardMaterial({color:0x7692a0,roughness:.2,emissive:this.mission.weather==='night'?0x5b5129:0x07141a,emissiveIntensity:this.mission.weather==='night'?1.5:.12});box(g,0,h/2,0,w,h,d,wall);box(g,0,h+.2,0,w+.25,.4,d+.25,mat(0x484542,.9));const rows=Math.min(8,Math.max(1,Math.floor(h/3)));for(let r=0;r<rows;r++)for(let c=-1;c<=1;c++)box(g,c*w*.25,2+r*2.7,-d/2-.04,Math.min(1.5,w*.17),1.25,.07,win);g.position.copy(p);g.rotation.y=yaw;this.group.add(g);}
  makeRoad(u,side,offset){const s=this.sample(u),q=s.p.clone().addScaledVector(s.right,side*offset),road=box(this.group,q.x,.02,q.z,7,.08,260,this.materials.road);road.rotation.y=s.yaw;for(let k=-4;k<=4;k++){const p=q.clone().addScaledVector(s.t,k*26).addScaledVector(s.right,k%2?1.5:-1.5),car=box(this.group,p.x,.56,p.z,1.8,1.08,4.2,mat([0x8a3030,0x315d7c,0xb5b3ad,0x242424][Math.abs(k)%4],.5,.1));car.rotation.y=s.yaw;}}
  stationSign(name){return canvasMaterial((ctx,w,h)=>{ctx.fillStyle='#19437f';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#fff';ctx.lineWidth=6;ctx.strokeRect(6,6,w-12,h-12);ctx.fillStyle='#fff';ctx.font='700 40px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(name,w/2,h/2);},640,140);}
  buildStations(){for(const st of this.mission.stations){const s=this.sample(st.u);for(const side of[-1,1]){const q=s.p.clone().addScaledVector(s.right,side<0?-3.35:7.9),pl=box(this.group,q.x,.34,q.z,3,.68,195,this.materials.concrete),ca=box(this.group,q.x,3.65,q.z,2.55,.16,112,this.materials.roof);pl.rotation.y=ca.rotation.y=s.yaw;const ep=q.clone().addScaledVector(s.right,side<0?1.25:-1.25),edge=box(this.group,ep.x,.72,ep.z,.42,.08,192,this.materials.edge);edge.rotation.y=s.yaw;for(let k=-48;k<=48;k+=16){const p=q.clone().addScaledVector(s.t,k),post=box(this.group,p.x,2,p.z,.11,4,.11,this.materials.metal);post.rotation.y=s.yaw;if(k%32===0){const lm=new THREE.MeshStandardMaterial({color:0xfff3d2,emissive:0xffd98e,emissiveIntensity:this.mission.weather==='night'?3:1});const l=box(this.group,p.x,3.35,p.z,.65,.08,.2,lm);l.rotation.y=s.yaw;}}}
      const signPos=s.p.clone().addScaledVector(s.right,st.platformSide==='left'?-4.2:3.1).addScaledVector(s.t,14),sign=mesh(this.group,new THREE.PlaneGeometry(3.6,.78),this.stationSign(st.name),false,false);sign.position.set(signPos.x,2.6,signPos.z);sign.rotation.y=s.yaw+(st.platformSide==='left'?Math.PI:0);
      const target=s.p.clone().addScaledVector(s.right,st.platformSide==='left'?-2.05:2.05);box(this.group,target.x,1.2,target.z,.11,2.4,.11,this.materials.metal);const board=box(this.group,target.x,2.35,target.z,.9,.62,.08,mat(0xf0efe9,.7));board.rotation.y=s.yaw;
    }}
  speedSign(value){return canvasMaterial((ctx,w,h)=>{ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(w/2,h/2,w*.4,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#222';ctx.lineWidth=12;ctx.stroke();ctx.fillStyle='#111';ctx.font='700 90px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(value),w/2,h/2+3);},256,256);}
  buildSignals(){const us=[];for(let u=.075;u<.97;u+=.09)us.push(u);us.forEach((u,i)=>{const s=this.sample(u),q=s.p.clone().addScaledVector(s.right,2.7),g=new THREE.Group();g.position.copy(q);g.rotation.y=s.yaw;this.group.add(g);box(g,0,1.65,0,.13,3.3,.13,this.materials.metal);box(g,0,3.4,0,.65,1.5,.34,this.materials.dark);const lamps=[];for(let k=0;k<3;k++){const lm=new THREE.MeshStandardMaterial({color:0x151515,emissive:0,emissiveIntensity:0}),l=mesh(g,new THREE.SphereGeometry(.16,18,12),lm);l.position.set(0,3.82-k*.42,-.2);lamps.push(l);}const state=i%5===3?'yellow':'green',sig={u,lamps,state};this.setSignal(sig,state);this.signals.push(sig);});for(const [u,v] of this.mission.speedZones.slice(1)){const s=this.sample(Math.min(.99,u+.002)),q=s.p.clone().addScaledVector(s.right,2.65);box(this.group,q.x,1.15,q.z,.1,2.3,.1,this.materials.metal);const sign=mesh(this.group,new THREE.PlaneGeometry(.78,.78),this.speedSign(v),false,false);sign.position.set(q.x,2.25,q.z);sign.rotation.y=s.yaw;}}
  setSignal(sig,state){sig.state=state;sig.lamps.forEach(l=>{l.material.color.set(0x141414);l.material.emissive.set(0);l.material.emissiveIntensity=0});const idx=state==='green'?2:state==='yellow'?1:0,col=state==='green'?0x35ff74:state==='yellow'?0xffc53d:0xff3535;sig.lamps[idx].material.color.set(col);sig.lamps[idx].material.emissive.set(col);sig.lamps[idx].material.emissiveIntensity=4;}
  buildTunnel(){if(!this.tunnel)return;for(let i=0;i<58;i++){const u=THREE.MathUtils.lerp(this.tunnel[0],this.tunnel[1],i/57),s=this.sample(u),g=new THREE.Group();g.position.copy(s.p);g.rotation.y=s.yaw;this.group.add(g);const a=mesh(g,new THREE.TorusGeometry(6,.42,8,24,Math.PI),mat(0x55595b,.96));a.rotation.z=Math.PI;box(g,-6,2.7,0,.45,5.4,7,mat(0x55595b,.96));box(g,6,2.7,0,.45,5.4,7,mat(0x55595b,.96));if(i%7===0)for(const side of[-1,1])box(g,side*4.9,3.3,0,.3,.12,.7,new THREE.MeshStandardMaterial({color:0xfff1c9,emissive:0xffd98d,emissiveIntensity:2.5}));}}
  buildTraffic(){for(const u of[.27,.69]){const g=new THREE.Group(),body=mat(0xc9ced1,.42,.28),blue=mat(0x315b7f,.4,.22),glass=new THREE.MeshStandardMaterial({color:0x254355,roughness:.14,emissive:this.mission.weather==='night'?0x071821:0,emissiveIntensity:.6});box(g,0,2,0,2.9,3.7,26,body);box(g,0,1,0,2.94,.7,26,blue);for(const side of[-1,1])for(let z=-10;z<=10;z+=3)box(g,side*1.46,2.45,z,.05,1.25,1.7,glass);g.userData.u=u;g.userData.speed=75+Math.random()*25;this.group.add(g);this.otherTrains.push(g);}}
  buildRain(){if(this.mission.weather!=='rain'){this.rain=null;return;}const count=2200,geo=new THREE.BufferGeometry(),a=new Float32Array(count*3);for(let i=0;i<count;i++){a[i*3]=(Math.random()-.5)*75;a[i*3+1]=Math.random()*34;a[i*3+2]=(Math.random()-.5)*105;}geo.setAttribute('position',new THREE.BufferAttribute(a,3));this.rain=new THREE.Points(geo,new THREE.PointsMaterial({color:0xcce7f2,size:.075,transparent:true,opacity:.52,depthWrite:false}));this.rain.frustumCulled=false;this.group.add(this.rain);}
  update(u,dt,cameraPos){for(const tr of this.otherTrains){tr.userData.u-=dt*tr.userData.speed/3.6/this.length;if(tr.userData.u<.02)tr.userData.u=.98;const s=this.sample(tr.userData.u,4.55);tr.position.copy(s.p);tr.rotation.y=s.yaw+Math.PI;}if(this.rain){this.rain.position.copy(cameraPos);this.rain.position.y-=8;const a=this.rain.geometry.attributes.position.array;for(let i=1;i<a.length;i+=3){a[i]-=dt*29;if(a[i]<0)a[i]=34;}this.rain.geometry.attributes.position.needsUpdate=true;}}
  dispose(){this.scene.remove(this.group);this.group.traverse(o=>o.geometry?.dispose?.());}
}
