import * as THREE from 'three';
import { Sky } from 'three/addons/objects/Sky.js';

const clamp=THREE.MathUtils.clamp;
function noiseTexture(colors,size=256,spread=10){const c=document.createElement('canvas');c.width=c.height=size;const x=c.getContext('2d'),img=x.createImageData(size,size),pal=colors.map(v=>{const q=new THREE.Color(v);return[q.r*255,q.g*255,q.b*255]});for(let i=0;i<size*size;i++){const p=pal[Math.floor(Math.random()*pal.length)],j=i*4;img.data[j]=p[0]+(Math.random()-.5)*spread;img.data[j+1]=p[1]+(Math.random()-.5)*spread;img.data[j+2]=p[2]+(Math.random()-.5)*spread;img.data[j+3]=255}x.putImageData(img,0,0);const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.colorSpace=THREE.SRGBColorSpace;return t}
function mat(c,r=.8,m=0,map=null){return new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m,map})}
function addMesh(parent,geo,material,cast=true,receive=true){const o=new THREE.Mesh(geo,material);o.castShadow=cast;o.receiveShadow=receive;parent.add(o);return o}
function box(parent,x,y,z,w,h,d,material){const o=addMesh(parent,new THREE.BoxGeometry(w,h,d),material);o.position.set(x,y,z);return o}
function apply(inst,i,pos,yaw=0,scale=[1,1,1]){const q=new THREE.Object3D();q.position.copy(pos);q.rotation.y=yaw;q.scale.set(...scale);q.updateMatrix();inst.setMatrixAt(i,q.matrix)}
function makeInst(parent,geo,material,count,cast=true,receive=true){const i=new THREE.InstancedMesh(geo,material,count);i.castShadow=cast;i.receiveShadow=receive;i.instanceMatrix.setUsage(THREE.StaticDrawUsage);parent.add(i);return i}

export class RailwayWorld{
  constructor(scene,mission,renderer){this.scene=scene;this.mission=mission;this.renderer=renderer;this.group=new THREE.Group();scene.add(this.group);this.route=new THREE.CatmullRomCurve3(mission.routePoints.map(p=>new THREE.Vector3(...p)),false,'catmullrom',.5);this.length=this.route.getLength();this.signals=[];this.otherTrains=[];this.platformTargets=[];this.tunnel=mission.tunnel||null;
    const grass=noiseTexture(['#405538','#506845','#5c744c','#384c33'],256,12),ballast=noiseTexture(['#686966','#79766f','#555956','#88837b'],256,22),concrete=noiseTexture(['#aaa9a2','#bbb7ad','#969995'],256,10),asphalt=noiseTexture(['#292d30','#33373a','#24282a'],256,8);grass.repeat.set(12,12);ballast.repeat.set(3,18);concrete.repeat.set(3,16);asphalt.repeat.set(2,12);
    this.m={grass:mat(0xffffff,1,0,grass),ballast:mat(0xffffff,1,0,ballast),concrete:mat(0xffffff,.96,0,concrete),asphalt:mat(0xffffff,.95,0,asphalt),rail:mat(0x737b80,.3,.82),sleeper:mat(0x4a4038,.95),metal:mat(0x42494d,.58,.38),wire:mat(0x1e2225,.48,.75),dark:mat(0x111417,.6,.15),roof:mat(0x3b444a,.6,.25),edge:mat(0xd7d1c3,.88),trunk:mat(0x5b422f,1),leaf:mat(0x365b34,1)};
    this.setupLighting();this.buildTrackInstanced();this.buildLandscape();this.buildStations();this.buildSignalsAndBoards();this.buildTunnel();this.buildTraffic();this.buildRain();
  }
  sample(u,offset=0){u=clamp(u,0,1);const p=this.route.getPointAt(u),t=this.route.getTangentAt(u).normalize(),right=new THREE.Vector3(-t.z,0,t.x).normalize();if(offset)p.addScaledVector(right,offset);return{p,t,right,yaw:Math.atan2(t.x,t.z)}}
  speedLimit(u){let v=this.mission.speedZones[0][1];for(const [a,b] of this.mission.speedZones)if(u>=a)v=b;return v}
  gradient(u){let v=0;for(const [a,b] of this.mission.gradients||[])if(u>=a)v=b;return v}
  zone(u){for(const [a,b,z] of this.mission.environment)if(u>=a&&u<b)return z;return'country'}
  inTunnel(u){return!!this.tunnel&&u>=this.tunnel[0]&&u<=this.tunnel[1]}

  setupLighting(){const night=this.mission.weather==='night',rain=this.mission.weather==='rain';const sky=new Sky();sky.scale.setScalar(450000);this.scene.add(sky);const u=sky.material.uniforms;u.turbidity.value=rain?13:6;u.rayleigh.value=night?.18:2.1;u.mieCoefficient.value=.008;u.mieDirectionalG.value=.82;const sunVec=new THREE.Vector3();sunVec.setFromSphericalCoords(1,THREE.MathUtils.degToRad(night?94:rain?73:53),THREE.MathUtils.degToRad(185));u.sunPosition.value.copy(sunVec);this.scene.fog=new THREE.FogExp2(night?0x0a1320:rain?0x8597a2:0xaabdc7,night?.0022:rain?.0021:.00105);this.scene.background=new THREE.Color(night?0x07101b:rain?0x8496a1:0xaec6d2);this.hemi=new THREE.HemisphereLight(night?0x35415b:0xe4f2ff,night?0x050608:0x33442e,night?.35:1.65);this.scene.add(this.hemi);this.sun=new THREE.DirectionalLight(night?0x8396bf:0xffefd0,night?.25:rain?.9:3.1);this.sun.position.set(-80,125,110);this.sun.castShadow=!night;this.sun.shadow.mapSize.set(2048,2048);this.sun.shadow.camera.left=-90;this.sun.shadow.camera.right=90;this.sun.shadow.camera.top=90;this.sun.shadow.camera.bottom=-90;this.scene.add(this.sun)}

  buildTrackInstanced(){const N=1050;const sleepers=[],rails=[],ballasts=[],poles=[],arms=[],wires=[],grounds=[];for(let i=0;i<N;i++){const u=i/(N-1),s=this.sample(u);if(i%2===0){sleepers.push([s.p.clone(),s.yaw]);sleepers.push([s.p.clone().addScaledVector(s.right,4.55),s.yaw])}if(i%6===0){ballasts.push([s.p.clone(),s.yaw]);ballasts.push([s.p.clone().addScaledVector(s.right,4.55),s.yaw])}if(i%3===0){for(const off of[-.76,.76,3.79,5.31])rails.push([s.p.clone().addScaledVector(s.right,off),s.yaw])}if(i%25===0){poles.push([s.p.clone().addScaledVector(s.right,-4.2),s.yaw]);poles.push([s.p.clone().addScaledVector(s.right,8.5),s.yaw]);arms.push([s.p.clone().addScaledVector(s.right,2.15),s.yaw])}if(i%12===0){wires.push([s.p.clone(),s.yaw]);wires.push([s.p.clone().addScaledVector(s.right,4.55),s.yaw])}}
    for(let i=0;i<115;i++){const s=this.sample(i/114);grounds.push([s.p.clone(),s.yaw])}
    const sl=makeInst(this.group,new THREE.BoxGeometry(2.72,.15,.27),this.m.sleeper,sleepers.length),rl=makeInst(this.group,new THREE.BoxGeometry(.095,.14,6.1),this.m.rail,rails.length),bl=makeInst(this.group,new THREE.BoxGeometry(4.35,.22,6.3),this.m.ballast,ballasts.length,false,true),po=makeInst(this.group,new THREE.BoxGeometry(.16,7,.16),this.m.metal,poles.length),ar=makeInst(this.group,new THREE.BoxGeometry(12.7,.12,.12),this.m.metal,arms.length),wi=makeInst(this.group,new THREE.BoxGeometry(.026,.026,15),this.m.wire,wires.length,false,false),gr=makeInst(this.group,new THREE.BoxGeometry(170,.9,170),this.m.grass,grounds.length,false,true);
    sleepers.forEach((v,i)=>{v[0].y=.04;apply(sl,i,v[0],v[1])});rails.forEach((v,i)=>{v[0].y=.16;apply(rl,i,v[0],v[1])});ballasts.forEach((v,i)=>{v[0].y=-.11;apply(bl,i,v[0],v[1])});poles.forEach((v,i)=>{v[0].y=3.5;apply(po,i,v[0],v[1])});arms.forEach((v,i)=>{v[0].y=6.85;apply(ar,i,v[0],v[1])});wires.forEach((v,i)=>{v[0].y=6.34;apply(wi,i,v[0],v[1])});grounds.forEach((v,i)=>{v[0].y=-.63;apply(gr,i,v[0],v[1])});[sl,rl,bl,po,ar,wi,gr].forEach(v=>v.instanceMatrix.needsUpdate=true);
  }

  buildLandscape(){const treeData=[];const buildings=[];for(let i=5;i<300;i++){const u=i/304,s=this.sample(u),zone=this.zone(u);for(const side of[-1,1]){if(Math.random()>.67)continue;const lateral=(zone==='dense'?12:15)+Math.random()*(zone==='country'?55:34);const p=s.p.clone().addScaledVector(s.right,side*lateral);if(zone==='wood'||zone==='country'||(zone==='suburb'&&Math.random()<.48)){treeData.push([p,.65+Math.random()*1.25]);if(Math.random()<.35){const q=p.clone().addScaledVector(s.right,side*(3+Math.random()*7));treeData.push([q,.55+Math.random()])}}else buildings.push([p,s.yaw,zone])}}
    const tr=makeInst(this.group,new THREE.BoxGeometry(.32,2.3,.32),this.m.trunk,treeData.length),cr=makeInst(this.group,new THREE.ConeGeometry(1.35,4.1,9),this.m.leaf,treeData.length);treeData.forEach(([p,sc],i)=>{const tp=p.clone();tp.y=1.15*sc;apply(tr,i,tp,0,[sc,sc,sc]);const cp=p.clone();cp.y=3.65*sc;apply(cr,i,cp,0,[sc,sc,sc])});tr.instanceMatrix.needsUpdate=cr.instanceMatrix.needsUpdate=true;
    buildings.forEach(([p,yaw,zone])=>this.makeBuilding(p,yaw,zone));for(const [u,side,off] of [[.08,1,20],[.20,-1,22],[.48,1,24],[.63,-1,19],[.86,1,21]])this.makeRoad(u,side,off)}
  makeBuilding(p,yaw,zone){const dense=zone==='dense'||zone==='urban',w=dense?8+Math.random()*13:6+Math.random()*5,d=dense?12+Math.random()*18:8+Math.random()*7,h=dense?11+Math.random()*26:5+Math.random()*5,g=new THREE.Group(),wall=mat(dense?[0xb0ada6,0x8f8c87,0xc1b7a8,0xa5abb0][Math.floor(Math.random()*4)]:[0xc2b7a6,0xb2a58f,0xc7c0b3][Math.floor(Math.random()*3)],.92),win=new THREE.MeshStandardMaterial({color:0x7893a1,roughness:.18,emissive:this.mission.weather==='night'?0x5f5326:0x08151c,emissiveIntensity:this.mission.weather==='night'?1.5:.12});box(g,0,h/2,0,w,h,d,wall);box(g,0,h+.18,0,w+.3,.34,d+.3,mat(0x494441,.9));const rows=Math.min(7,Math.max(1,Math.floor(h/3)));for(let r=0;r<rows;r++)for(let c=-1;c<=1;c++)box(g,c*w*.25,2.1+r*2.7,-d/2-.04,Math.min(1.45,w*.17),1.3,.07,win);g.position.copy(p);g.rotation.y=yaw;this.group.add(g)}
  makeRoad(u,side,offset){const s=this.sample(u),q=s.p.clone().addScaledVector(s.right,side*offset),road=box(this.group,q.x,.02,q.z,7,.08,250,this.m.asphalt);road.rotation.y=s.yaw;for(let k=-4;k<=4;k++){const p=q.clone().addScaledVector(s.t,k*25).addScaledVector(s.right,k%2?1.5:-1.5),car=box(this.group,p.x,.58,p.z,1.8,1.1,4.2,mat([0x8c3030,0x315b7c,0xbab7ae,0x292929][Math.abs(k)%4],.48,.1));car.rotation.y=s.yaw}}

  stationMaterial(text){const c=document.createElement('canvas');c.width=640;c.height=140;const x=c.getContext('2d');x.fillStyle='#15417d';x.fillRect(0,0,640,140);x.strokeStyle='white';x.lineWidth=7;x.strokeRect(7,7,626,126);x.fillStyle='white';x.font='700 44px Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(text,320,70);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return new THREE.MeshBasicMaterial({map:t,toneMapped:false})}
  buildStations(){for(const st of this.mission.stations){const s=this.sample(st.u);for(const side of[-1,1]){const q=s.p.clone().addScaledVector(s.right,side<0?-3.3:7.85),pl=box(this.group,q.x,.35,q.z,3,.7,190,this.m.concrete),ca=box(this.group,q.x,3.7,q.z,2.5,.18,112,this.m.roof);pl.rotation.y=ca.rotation.y=s.yaw;const edgePos=q.clone().addScaledVector(s.right,side<0?1.25:-1.25),ed=box(this.group,edgePos.x,.73,edgePos.z,.42,.08,188,this.m.edge);ed.rotation.y=s.yaw;for(let k=-48;k<=48;k+=16){const p=q.clone().addScaledVector(s.t,k),post=box(this.group,p.x,2,p.z,.12,4,.12,this.m.metal);post.rotation.y=s.yaw;if(k%32===0){const lm=new THREE.MeshStandardMaterial({color:0xfff4d3,emissive:0xffdda0,emissiveIntensity:this.mission.weather==='night'?3:1});const l=box(this.group,p.x,3.4,p.z,.7,.08,.22,lm);l.rotation.y=s.yaw}}}
      const signPos=s.p.clone().addScaledVector(s.right,st.platformSide==='left'?-4.2:3.0).addScaledVector(s.t,15),sign=addMesh(this.group,new THREE.PlaneGeometry(3.5,.78),this.stationMaterial(st.name),false,false);sign.position.set(signPos.x,2.65,signPos.z);sign.rotation.y=s.yaw+(st.platformSide==='left'?Math.PI:0);const target=s.p.clone().addScaledVector(s.right,st.platformSide==='left'?-2.05:2.05);box(this.group,target.x,1.2,target.z,.11,2.4,.11,this.m.metal);const board=box(this.group,target.x,2.35,target.z,.9,.62,.08,mat(0xf1f0ea,.72));board.rotation.y=s.yaw;this.platformTargets.push({station:st,p:s.p.clone()})}}

  speedBoardMaterial(v){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d');x.fillStyle='#fff';x.beginPath();x.arc(128,128,104,0,Math.PI*2);x.fill();x.strokeStyle='#202020';x.lineWidth=13;x.stroke();x.fillStyle='#111';x.font='700 100px Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(String(v),128,133);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return new THREE.MeshBasicMaterial({map:t,toneMapped:false})}
  buildSignalsAndBoards(){const us=[];for(let u=.075;u<.97;u+=.09)us.push(u);us.forEach((u,i)=>{const s=this.sample(u),q=s.p.clone().addScaledVector(s.right,2.7),g=new THREE.Group();g.position.copy(q);g.rotation.y=s.yaw;this.group.add(g);box(g,0,1.65,0,.13,3.3,.13,this.m.metal);box(g,0,3.4,0,.65,1.5,.34,this.m.dark);const lamps=[];for(let k=0;k<3;k++){const lm=new THREE.MeshStandardMaterial({color:0x151515,emissive:0,emissiveIntensity:0}),l=addMesh(g,new THREE.SphereGeometry(.16,18,12),lm);l.position.set(0,3.82-k*.42,-.20);lamps.push(l)}const state=i%5===3?'yellow':'green',sig={u,lamps,state};this.setSignal(sig,state);this.signals.push(sig)});
    for(const [u,v] of this.mission.speedZones.slice(1)){const s=this.sample(Math.min(.99,u+.002)),q=s.p.clone().addScaledVector(s.right,2.65);box(this.group,q.x,1.15,q.z,.1,2.3,.1,this.m.metal);const sign=addMesh(this.group,new THREE.PlaneGeometry(.78,.78),this.speedBoardMaterial(v),false,false);sign.position.set(q.x,2.25,q.z);sign.rotation.y=s.yaw;}}
  setSignal(sig,state){sig.state=state;sig.lamps.forEach(l=>{l.material.color.set(0x141414);l.material.emissive.set(0);l.material.emissiveIntensity=0});const idx=state==='green'?2:state==='yellow'?1:0,col=state==='green'?0x35ff74:state==='yellow'?0xffc53d:0xff3535;sig.lamps[idx].material.color.set(col);sig.lamps[idx].material.emissive.set(col);sig.lamps[idx].material.emissiveIntensity=4}
  upcomingSignal(u){return this.signals.find(s=>s.u>u)||null}

  buildTunnel(){if(!this.tunnel)return;for(let i=0;i<58;i++){const u=THREE.MathUtils.lerp(this.tunnel[0],this.tunnel[1],i/57),s=this.sample(u),g=new THREE.Group();g.position.copy(s.p);g.rotation.y=s.yaw;this.group.add(g);const a=addMesh(g,new THREE.TorusGeometry(6,.42,8,24,Math.PI),mat(0x55595b,.96));a.rotation.z=Math.PI;box(g,-6,2.7,0,.45,5.4,7,mat(0x55595b,.96));box(g,6,2.7,0,.45,5.4,7,mat(0x55595b,.96));if(i%7===0)for(const side of[-1,1])box(g,side*4.9,3.3,0,.3,.12,.7,new THREE.MeshStandardMaterial({color:0xfff1c9,emissive:0xffd98d,emissiveIntensity:2.5}))}}
  buildTraffic(){for(const u of[.27,.69]){const g=new THREE.Group(),body=mat(0xc9ced1,.42,.28),blue=mat(0x315b7f,.4,.22),glass=new THREE.MeshStandardMaterial({color:0x254355,roughness:.14,emissive:this.mission.weather==='night'?0x071821:0,emissiveIntensity:.6});box(g,0,2,0,2.9,3.7,26,body);box(g,0,1.0,0,2.94,.7,26,blue);for(const side of[-1,1])for(let z=-10;z<=10;z+=3)box(g,side*1.46,2.45,z,.05,1.25,1.7,glass);g.userData.u=u;g.userData.speed=75+Math.random()*25;this.group.add(g);this.otherTrains.push(g)}}
  buildRain(){if(this.mission.weather!=='rain'){this.rain=null;return}const count=2200,geo=new THREE.BufferGeometry(),a=new Float32Array(count*3);for(let i=0;i<count;i++){a[i*3]=(Math.random()-.5)*75;a[i*3+1]=Math.random()*34;a[i*3+2]=(Math.random()-.5)*105}geo.setAttribute('position',new THREE.BufferAttribute(a,3));this.rain=new THREE.Points(geo,new THREE.PointsMaterial({color:0xcce7f2,size:.075,transparent:true,opacity:.52,depthWrite:false}));this.rain.frustumCulled=false;this.group.add(this.rain)}
  update(u,dt,cameraPos){for(const tr of this.otherTrains){tr.userData.u-=dt*tr.userData.speed/3.6/this.length;if(tr.userData.u<.02)tr.userData.u=.98;const s=this.sample(tr.userData.u,4.55);tr.position.copy(s.p);tr.rotation.y=s.yaw+Math.PI}if(this.rain){this.rain.position.copy(cameraPos);this.rain.position.y-=8;const a=this.rain.geometry.attributes.position.array;for(let i=1;i<a.length;i+=3){a[i]-=dt*29;if(a[i]<0)a[i]=34}this.rain.geometry.attributes.position.needsUpdate=true}}
  dispose(){this.scene.remove(this.group);this.group.traverse(o=>o.geometry?.dispose?.())}
}
